apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
      - name: app
        image: 39215068/todo-app:1.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: "/app/static"
            name: staticfiles
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
